version: '3'

services:
  clion_remote_env:
    build:
      context: .
      dockerfile: Dockerfile-alpine
    image: clion/remote-alpine:1.0
    container_name: clion_remote_env
    ports:
      - "127.0.0.1:2222:22"
    cap_add:
      - sys_ptrace
    privileged: true
    command: ["/usr/sbin/sshd", "-D", "-f", "/etc/sshd_config_test_clion"]
    restart: unless-stopped